

server:
  port: 10001
  servlet:
    context-path: /nacos-spring-boot
#  address: localhost




nacos:
  config:
    server-addr: nacos.com:8848
#    server-addr: 172.16.5.1:8848
    # nacos的uuid
    group: test
    namespace: 8e1690ee-2eff-4bed-bc85-dc585270775d
    auto-refresh: true
    config-retry-time: 2000
    config-long-poll-timeout: 50000
    enable-remote-sync-config: true
    type: yaml

#  management.endpoints.web.exposure.include=*
#  management.endpoint.health.show-details=always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
